#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "ru.mss.app.ktor.ApplicationKt.module"
#  logger: "kmp"
#  urls:
#    - "http://127.0.0.1:8080/v1"
#    - "http://0.0.0.0:8080/v1"
#    - "http://192.168.0.182:8080/v1"
musicsearchservice:
  repository:
    test: "$DB_TYPE_TEST:inmemory"
    prod: "$DB_TYPE_PROD:postgres"
    # prod: psql
    psql:
      password: musicsearchservice-pass
      schema: musicsearchservice
      url: "jdbc:postgresql://postgresql:5432/musicsearchservice"
      user: postgres

jwt:
  issuer: "http://keycloak:8080/auth/realms/otus-musicsearchservice"
  audience: "topic-users"
  realm: "otus-musicsearchservice"
  clientId: "otus-musicsearchservice"
  certUrl: "http://keycloak:8080/auth/realms/otus-musicsearchservice/protocol/openid-connect/certs"